### ISSUE TITLE
Model download link is broken

### ISSUE THREAD

**Issue by mohammed-elkomy** [RanaMalhas/QRCD#1]
SA Dr Rana, 
First, congratulations on your accepted paper 🎊! 

I was one of the participants in the QRCD competition and currently extending my research on the same problem.
I'm so excited about your work and I would like to include CL-AraBERT in my study but the download link is broken, may you please check the link?

I came across [this published checkpoint ](https://huggingface.co/qahq/CL-AraBERTv0.1-base) on HF, is it the same model with the reported results in the paper?

Thanks so much

**Comment by RanaMalhas** [comment]
وعليكم السلام ورحمة الله وبركاته

Thank you for alerting me about the broken link!

I have replied to your message on LinkedIn that also addresses your inquiry about the hugging face model.

All the best with your research.

Rana Malhas


From: Mohammed Alaa El komy ***@***.***>
Sent: Sunday, September 11, 2022 4:55 PM
To: RanaMalhas/QRCD ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ALERT: Non-QU Sender] [RanaMalhas/QRCD] Model download link is borken (Issue #1)


SA Dr Rana,
First, congratulations on your accepted paper 🎊!

I was one of the participants in the QRCD competition and currently extending my research on the same problem.
I'm so excited about your work and I would like to include CL-AraBERT in my study but the download link is broken, may you please check the link?

I came across this published checkpoint <https://huggingface.co/qahq/CL-AraBERTv0.1-base> on HF, is it the same model with the reported results in the paper?

Thanks so much
